services:
  supabase-grafana:
    build: ./
    # ports:
    #   - 3000
    expose:
      - "3000"
    environment:
      SUPABASE_ACCESS_TOKEN: ${SUPABASE_ACCESS_TOKEN}
      SUPABASE_ORGANIZATION_ID: ${SUPABASE_ORGANIZATION_ID}
      SUPABASE_PROJECT_REF: ${SUPABASE_PROJECT_REF}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      PASSWORD_PROTECTED: ${PASSWORD_PROTECTED}
      GRAFANA_PASSWORD: ${GRAFANA_PASSWORD}
      GF_SERVER_HTTP_ADDR: 0.0.0.0
      GF_SERVER_HTTP_PORT: 3000
      GF_SERVER_ROOT_URL: https://grafana.influtics.com
    volumes:
      - ./data:/data
