version: '3.7'
services:
  collector:
    image: ghcr.io/supabase/supabase-grafana:latest
    env_file: .env
    ports:
      - "9000:9000"      # metrics endpoint only
    volumes:
      - .//data

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
